name: Run AWS Glue Job

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Glue job name to run'
        required: true
        default: 'wistia_events_incremental'

jobs:
  run-glue:
    runs-on: ubuntu-latest

    steps:
      # Optional: checkout your repo (if needed)
      - name: Checkout repo
        uses: actions/checkout@v3

      # Run your Glue job
      - name: Call AWS Glue Job
        env:
          AWS_REGION: us-east-1
        run: |
          aws glue start-job-run \
            --region $AWS_REGION \
            --job-name "${{ github.event.inputs.job_name }}"
